$output = @()

$header = "Handle,Title,Body (HTML),Vendor,Type,Tags,Published,Option1 Name,Option1 Value,Variant SKU,Variant Grams,Variant Inventory Tracker,Variant Inventory Qty,Variant Inventory Policy,Variant Fulfillment Service,Variant Price,Variant Compare At Price,Variant Requires Shipping,Variant Taxable,Image Src,Image Position,Image Alt Text,Status"

$tamanhos = @("P","M","G","GG","XGG")

function New-Produto {
    param($handle, $titulo, $descricao, $tipo, $tags, $preco, $precoComparativo)
    $rows = @()
    $first = $true
    foreach ($tam in $tamanhos) {
        $sku = "$handle-$tam".ToUpper()
        if ($first) {
            $rows += "$handle,`"$titulo`",`"$descricao`",Manto dos Craques,$tipo,`"$tags`",TRUE,Tamanho,$tam,$sku,300,shopify,10,deny,manual,$preco,$precoComparativo,TRUE,TRUE,,,,$titulo,active"
            $first = $false
        } else {
            $rows += "$handle,,,,,,,,,$tam,$sku,300,shopify,10,deny,manual,$preco,$precoComparativo,TRUE,TRUE,,,,active"
        }
    }
    return $rows
}

$produtos = @(
    # ===== COPA DO MUNDO 2026 - SELEÇÕES =====
    @{ h="camisa-brasil-home-2026"; t="Camisa Brasil Home 2026 | Copa do Mundo"; d="A camisa oficial da Seleção Brasileira para a Copa do Mundo 2026. Tecido dry-fit de alta performance, emblema bordado e as cores verde e amarelo que representam o país do futebol."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,brasil,america-do-sul"; p="149.90"; pc="199.90" },
    @{ h="camisa-brasil-away-2026"; t="Camisa Brasil Away 2026 | Copa do Mundo"; d="Versão alternativa da Seleção Brasileira para a Copa do Mundo 2026. Design moderno em azul, representando o céu e a grandiosidade do futebol brasileiro."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,brasil,america-do-sul"; p="149.90"; pc="199.90" },
    @{ h="camisa-brasil-third-2026"; t="Camisa Brasil Third 2026 | Copa do Mundo"; d="Terceira camisa da Seleção Brasileira para a Copa do Mundo 2026. Edição especial com design arrojado e identidade visual única."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,brasil,america-do-sul"; p="149.90"; pc="199.90" },
    @{ h="camisa-argentina-home-2026"; t="Camisa Argentina Home 2026 | Copa do Mundo"; d="A camisa oficial da Seleção Argentina para a Copa do Mundo 2026. As tradicionais listras azul e branco com o escudo da AFA. Vista a camisa do atual campeão mundial."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,argentina,america-do-sul"; p="149.90"; pc="199.90" },
    @{ h="camisa-argentina-away-2026"; t="Camisa Argentina Away 2026 | Copa do Mundo"; d="Versão alternativa da Argentina para a Copa 2026. Design diferenciado mantendo a identidade albiceleste."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,argentina,america-do-sul"; p="149.90"; pc="199.90" },
    @{ h="camisa-franca-home-2026"; t="Camisa França Home 2026 | Copa do Mundo"; d="A camisa oficial da Seleção Francesa para a Copa do Mundo 2026. O clássico azul da Les Bleus com Mbappé e companhia na busca pelo tricampeonato."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,franca,europa"; p="149.90"; pc="199.90" },
    @{ h="camisa-franca-away-2026"; t="Camisa França Away 2026 | Copa do Mundo"; d="Versão alternativa da França para a Copa 2026. Branco elegante para os jogos fora de casa da atual bicampeã mundial."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,franca,europa"; p="149.90"; pc="199.90" },
    @{ h="camisa-alemanha-home-2026"; t="Camisa Alemanha Home 2026 | Copa do Mundo"; d="A camisa oficial da Seleção Alemã para a Copa do Mundo 2026. O tradicional branco da Die Mannschaft em busca do quinto título mundial."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,alemanha,europa"; p="149.90"; pc="199.90" },
    @{ h="camisa-alemanha-away-2026"; t="Camisa Alemanha Away 2026 | Copa do Mundo"; d="Versão alternativa da Alemanha para a Copa 2026. Design moderno com as cores secundárias da seleção germânica."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,alemanha,europa"; p="149.90"; pc="199.90" },
    @{ h="camisa-espanha-home-2026"; t="Camisa Espanha Home 2026 | Copa do Mundo"; d="A camisa oficial da Seleção Espanhola para a Copa do Mundo 2026. O vibrante vermelho da Roja com o atual campeão europeu."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,espanha,europa"; p="149.90"; pc="199.90" },
    @{ h="camisa-espanha-away-2026"; t="Camisa Espanha Away 2026 | Copa do Mundo"; d="Versão alternativa da Espanha para a Copa 2026. Azul escuro com o escudo da Federación Española."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,espanha,europa"; p="149.90"; pc="199.90" },
    @{ h="camisa-portugal-home-2026"; t="Camisa Portugal Home 2026 | Copa do Mundo"; d="A camisa oficial de Portugal para a Copa do Mundo 2026. O vermelho e verde com Cristiano Ronaldo e a nova geração portuguesa."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,portugal,europa"; p="149.90"; pc="199.90" },
    @{ h="camisa-portugal-away-2026"; t="Camisa Portugal Away 2026 | Copa do Mundo"; d="Versão alternativa de Portugal para a Copa 2026. Branco clean com detalhes em verde, representando as cores nacionais."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,portugal,europa"; p="149.90"; pc="199.90" },
    @{ h="camisa-inglaterra-home-2026"; t="Camisa Inglaterra Home 2026 | Copa do Mundo"; d="A camisa oficial da Seleção Inglesa para a Copa do Mundo 2026. O eterno branco dos Three Lions, sediando o torneio em busca do segundo título."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,inglaterra,europa"; p="149.90"; pc="199.90" },
    @{ h="camisa-italia-home-2026"; t="Camisa Itália Home 2026 | Copa do Mundo"; d="A camisa oficial da Seleção Italiana para a Copa do Mundo 2026. O tradicional azul Azzurri dos tetracampeões mundiais."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,italia,europa"; p="149.90"; pc="199.90" },
    @{ h="camisa-holanda-home-2026"; t="Camisa Holanda Home 2026 | Copa do Mundo"; d="A camisa oficial da Seleção Holandesa para a Copa do Mundo 2026. O laranja intenso da Oranje com uma das seleções mais técnicas da Europa."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,holanda,europa"; p="149.90"; pc="199.90" },
    @{ h="camisa-uruguai-home-2026"; t="Camisa Uruguai Home 2026 | Copa do Mundo"; d="A camisa oficial do Uruguai para a Copa do Mundo 2026. O celeste característico da Celeste Olímpica, bicampeã mundial."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,uruguai,america-do-sul"; p="149.90"; pc="199.90" },
    @{ h="camisa-colombia-home-2026"; t="Camisa Colômbia Home 2026 | Copa do Mundo"; d="A camisa oficial da Colômbia para a Copa do Mundo 2026. O amarelo vibrante dos Cafeteros com James Rodríguez e a nova geração."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,colombia,america-do-sul"; p="149.90"; pc="199.90" },
    @{ h="camisa-mexico-home-2026"; t="Camisa México Home 2026 | Copa do Mundo"; d="A camisa oficial do México para a Copa do Mundo 2026, sediada no próprio país. O verde e vermelho do El Tri perante sua torcida."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,mexico,america-do-norte"; p="149.90"; pc="199.90" },
    @{ h="camisa-eua-home-2026"; t="Camisa EUA Home 2026 | Copa do Mundo"; d="A camisa oficial dos Estados Unidos para a Copa do Mundo 2026, co-sede do torneio. Os Stars and Stripes no futebol americano."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,eua,america-do-norte"; p="149.90"; pc="199.90" },
    @{ h="camisa-croacia-home-2026"; t="Camisa Croácia Home 2026 | Copa do Mundo"; d="A camisa oficial da Croácia para a Copa do Mundo 2026. O icônico xadrez vermelho e branco da vice-campeã de 2018."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,croacia,europa"; p="149.90"; pc="199.90" },
    @{ h="camisa-belgica-home-2026"; t="Camisa Bélgica Home 2026 | Copa do Mundo"; d="A camisa oficial da Bélgica para a Copa do Mundo 2026. O vermelho dos Red Devils em sua busca pelo primeiro título mundial."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,belgica,europa"; p="149.90"; pc="199.90" },
    @{ h="camisa-japao-home-2026"; t="Camisa Japão Home 2026 | Copa do Mundo"; d="A camisa oficial do Japão para a Copa do Mundo 2026. O azul samurai com uma das seleções mais surpreendentes do futebol asiático."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,japao,asia"; p="149.90"; pc="199.90" },
    @{ h="camisa-marrocos-home-2026"; t="Camisa Marrocos Home 2026 | Copa do Mundo"; d="A camisa oficial de Marrocos para a Copa do Mundo 2026. Os Lions de Atlas, semifinalistas em 2022, prontos para fazer história novamente."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,marrocos,africa"; p="149.90"; pc="199.90" },
    @{ h="camisa-senegal-home-2026"; t="Camisa Senegal Home 2026 | Copa do Mundo"; d="A camisa oficial do Senegal para a Copa do Mundo 2026. O branco e verde dos Leões do Teranga, campeões africanos."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,senegal,africa"; p="149.90"; pc="199.90" },
    @{ h="camisa-venezuela-home-2026"; t="Camisa Venezuela Home 2026 | Copa do Mundo"; d="A camisa oficial da Venezuela para a Copa do Mundo 2026. A Vinotinto em sua estreia no maior torneio de futebol do mundo."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,venezuela,america-do-sul"; p="149.90"; pc="199.90" },
    @{ h="camisa-equador-home-2026"; t="Camisa Equador Home 2026 | Copa do Mundo"; d="A camisa oficial do Equador para a Copa do Mundo 2026. A La Tri com sua torcida apaixonada rumo ao torneio."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,equador,america-do-sul"; p="149.90"; pc="199.90" },
    @{ h="camisa-canada-home-2026"; t="Camisa Canadá Home 2026 | Copa do Mundo"; d="A camisa oficial do Canadá para a Copa do Mundo 2026, co-sede do torneio. O vermelho canadense numa Copa jogada em casa."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,canada,america-do-norte"; p="149.90"; pc="199.90" },
    @{ h="camisa-suica-home-2026"; t="Camisa Suíça Home 2026 | Copa do Mundo"; d="A camisa oficial da Suíça para a Copa do Mundo 2026. O vermelho e branco da Nati, sempre presente nos grandes torneios europeus."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,suica,europa"; p="149.90"; pc="199.90" },
    @{ h="camisa-dinamarca-home-2026"; t="Camisa Dinamarca Home 2026 | Copa do Mundo"; d="A camisa oficial da Dinamarca para a Copa do Mundo 2026. O vermelho dinamarquês com Eriksen e a geração que encantou a Europa."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,dinamarca,europa"; p="149.90"; pc="199.90" },
    @{ h="camisa-nigeria-home-2026"; t="Camisa Nigéria Home 2026 | Copa do Mundo"; d="A camisa oficial da Nigéria para a Copa do Mundo 2026. As Super Águias com um dos uniformes mais icônicos do futebol africano."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,nigeria,africa"; p="149.90"; pc="199.90" },
    @{ h="camisa-australia-home-2026"; t="Camisa Austrália Home 2026 | Copa do Mundo"; d="A camisa oficial da Austrália para a Copa do Mundo 2026. Os Socceroos com Sam Kerr e a nova geração australiana."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,australia,oceania"; p="149.90"; pc="199.90" },
    @{ h="camisa-chile-home-2026"; t="Camisa Chile Home 2026 | Copa do Mundo"; d="A camisa oficial do Chile para a Copa do Mundo 2026. O vermelho e branco da Roja em busca de nova glória sul-americana."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,chile,america-do-sul"; p="149.90"; pc="199.90" },
    @{ h="camisa-paraguai-home-2026"; t="Camisa Paraguai Home 2026 | Copa do Mundo"; d="A camisa oficial do Paraguai para a Copa do Mundo 2026. A Albirroja numa Copa repleta de rivalidades sul-americanas."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,paraguai,america-do-sul"; p="149.90"; pc="199.90" },
    @{ h="camisa-peru-home-2026"; t="Camisa Peru Home 2026 | Copa do Mundo"; d="A camisa oficial do Peru para a Copa do Mundo 2026. A Blanquirroja com Paolo Guerrero e a paixão peruana pelo futebol."; tp="Seleções"; tags="copa-do-mundo-2026,selecoes,peru,america-do-sul"; p="149.90"; pc="199.90" },

    # ===== CLUBES BRASILEIROS =====
    @{ h="camisa-flamengo-home-2526"; t="Camisa Flamengo Home 2025/26 | Mengão"; d="A camisa oficial do Clube de Regatas do Flamengo para a temporada 2025/26. As cores rubro-negras do maior clube do Brasil com a Nação Mais Querida."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,flamengo,rio-de-janeiro,serie-a"; p="129.90"; pc="179.90" },
    @{ h="camisa-flamengo-away-2526"; t="Camisa Flamengo Away 2025/26 | Mengão"; d="Versão alternativa do Flamengo para a temporada 2025/26. Design diferenciado mantendo o espírito rubro-negro da Nação mais querida do Brasil."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,flamengo,rio-de-janeiro,serie-a"; p="129.90"; pc="179.90" },
    @{ h="camisa-flamengo-third-2526"; t="Camisa Flamengo Third 2025/26 | Mengão"; d="Terceira camisa do Flamengo para a temporada 2025/26. Edição especial com design exclusivo para jogos internacionais."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,flamengo,rio-de-janeiro,serie-a"; p="129.90"; pc="179.90" },
    @{ h="camisa-corinthians-home-2526"; t="Camisa Corinthians Home 2025/26 | Timão"; d="A camisa oficial do Sport Club Corinthians Paulista para a temporada 2025/26. O branco imaculado do Timão com a Fiel Torcida."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,corinthians,sao-paulo,serie-a"; p="129.90"; pc="179.90" },
    @{ h="camisa-corinthians-away-2526"; t="Camisa Corinthians Away 2025/26 | Timão"; d="Versão alternativa do Corinthians para 2025/26. O preto elegante do Timão para os jogos fora de casa."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,corinthians,sao-paulo,serie-a"; p="129.90"; pc="179.90" },
    @{ h="camisa-palmeiras-home-2526"; t="Camisa Palmeiras Home 2025/26 | Verdão"; d="A camisa oficial da Sociedade Esportiva Palmeiras para a temporada 2025/26. O verde alviverde do maior campeão brasileiro recente."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,palmeiras,sao-paulo,serie-a"; p="129.90"; pc="179.90" },
    @{ h="camisa-palmeiras-away-2526"; t="Camisa Palmeiras Away 2025/26 | Verdão"; d="Versão alternativa do Palmeiras para 2025/26. Design diferenciado para o bicampeão da Libertadores."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,palmeiras,sao-paulo,serie-a"; p="129.90"; pc="179.90" },
    @{ h="camisa-sao-paulo-home-2526"; t="Camisa São Paulo Home 2025/26 | SPFC"; d="A camisa oficial do São Paulo Futebol Clube para a temporada 2025/26. Tricolor paulista com as cores branco, vermelho e preto."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,sao-paulo,serie-a,tricolor"; p="129.90"; pc="179.90" },
    @{ h="camisa-sao-paulo-away-2526"; t="Camisa São Paulo Away 2025/26 | SPFC"; d="Versão alternativa do São Paulo FC para 2025/26. Elegância tricolor para os jogos fora do Morumbis."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,sao-paulo,serie-a,tricolor"; p="129.90"; pc="179.90" },
    @{ h="camisa-botafogo-home-2526"; t="Camisa Botafogo Home 2025/26 | Estrela Solitária"; d="A camisa oficial do Botafogo de Futebol e Regatas para a temporada 2025/26. O Glorioso com o estrela solitária brilhando novamente."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,botafogo,rio-de-janeiro,serie-a"; p="129.90"; pc="179.90" },
    @{ h="camisa-botafogo-away-2526"; t="Camisa Botafogo Away 2025/26 | Estrela Solitária"; d="Versão alternativa do Botafogo para 2025/26. O branco e preto do Glorioso nas competições nacionais e internacionais."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,botafogo,rio-de-janeiro,serie-a"; p="129.90"; pc="179.90" },
    @{ h="camisa-vasco-home-2526"; t="Camisa Vasco da Gama Home 2025/26 | Cruz-Maltino"; d="A camisa oficial do Club de Regatas Vasco da Gama para a temporada 2025/26. O Cruz-Maltino com sua história gloriosa no futebol brasileiro."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,vasco,rio-de-janeiro,serie-a"; p="129.90"; pc="179.90" },
    @{ h="camisa-gremio-home-2526"; t="Camisa Grêmio Home 2025/26 | Tricolor Gaúcho"; d="A camisa oficial do Grêmio Foot-Ball Porto Alegrense para a temporada 2025/26. O tricolor imortal com as cores azul, preto e branco."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,gremio,rio-grande-do-sul,serie-a"; p="129.90"; pc="179.90" },
    @{ h="camisa-gremio-away-2526"; t="Camisa Grêmio Away 2025/26 | Tricolor Gaúcho"; d="Versão alternativa do Grêmio para 2025/26. O tricolor gaúcho em uma versão moderna para os jogos fora da Arena."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,gremio,rio-grande-do-sul,serie-a"; p="129.90"; pc="179.90" },
    @{ h="camisa-internacional-home-2526"; t="Camisa Internacional Home 2025/26 | Colorado"; d="A camisa oficial do Sport Club Internacional para a temporada 2025/26. O Colorado com o vermelho que representa paixão e garra gaúcha."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,internacional,rio-grande-do-sul,serie-a"; p="129.90"; pc="179.90" },
    @{ h="camisa-atletico-mg-home-2526"; t="Camisa Atlético Mineiro Home 2025/26 | Galo"; d="A camisa oficial do Clube Atlético Mineiro para a temporada 2025/26. O Galo com o preto e branco do bicampeão da Copa do Brasil."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,atletico-mg,minas-gerais,serie-a"; p="129.90"; pc="179.90" },
    @{ h="camisa-atletico-mg-away-2526"; t="Camisa Atlético Mineiro Away 2025/26 | Galo"; d="Versão alternativa do Atlético Mineiro para 2025/26. Design moderno para o clube que dominou o futebol brasileiro."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,atletico-mg,minas-gerais,serie-a"; p="129.90"; pc="179.90" },
    @{ h="camisa-cruzeiro-home-2526"; t="Camisa Cruzeiro Home 2025/26 | Raposa"; d="A camisa oficial do Cruzeiro Esporte Clube para a temporada 2025/26. A Raposa com o azul celeste e a estrela de quatro pontas."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,cruzeiro,minas-gerais,serie-a"; p="129.90"; pc="179.90" },
    @{ h="camisa-fluminense-home-2526"; t="Camisa Fluminense Home 2025/26 | Flu"; d="A camisa oficial do Fluminense Football Club para a temporada 2025/26. O Tricolor das Laranjeiras com as cores vinho, verde e branco."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,fluminense,rio-de-janeiro,serie-a"; p="129.90"; pc="179.90" },
    @{ h="camisa-fortaleza-home-2526"; t="Camisa Fortaleza Home 2025/26 | Leão"; d="A camisa oficial do Fortaleza Esporte Clube para a temporada 2025/26. O Leão do Pici representando o Nordeste no cenário nacional."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,fortaleza,ceara,serie-a"; p="129.90"; pc="179.90" },
    @{ h="camisa-bahia-home-2526"; t="Camisa Bahia Home 2025/26 | Esquadrão"; d="A camisa oficial do Esporte Clube Bahia para a temporada 2025/26. O Esquadrão de Aço com as cores azul, vermelho e branco."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,bahia,serie-a,nordeste"; p="129.90"; pc="179.90" },
    @{ h="camisa-santos-home-2526"; t="Camisa Santos Home 2025/26 | Peixe"; d="A camisa oficial do Santos Futebol Clube para a temporada 2025/26. O Peixe da Vila Belmiro com a tradição do clube de Pelé."; tp="Clubes Brasileiros"; tags="clubes-brasileiros,santos,sao-paulo,serie-a"; p="129.90"; pc="179.90" },

    # ===== CLUBES EUROPEUS =====
    @{ h="camisa-real-madrid-home-2526"; t="Camisa Real Madrid Home 2025/26 | Los Blancos"; d="A camisa oficial do Real Madrid para a temporada 2025/26. O branco eterno do maior clube do mundo com Vinicius Jr., Rodrygo e Endrick."; tp="Clubes Europeus"; tags="clubes-europeus,real-madrid,espanha,la-liga,champions-league"; p="129.90"; pc="179.90" },
    @{ h="camisa-real-madrid-away-2526"; t="Camisa Real Madrid Away 2025/26 | Los Blancos"; d="Versão alternativa do Real Madrid para 2025/26. Design moderno para os jogos fora do Santiago Bernabéu."; tp="Clubes Europeus"; tags="clubes-europeus,real-madrid,espanha,la-liga"; p="129.90"; pc="179.90" },
    @{ h="camisa-barcelona-home-2526"; t="Camisa Barcelona Home 2025/26 | Barça"; d="A camisa oficial do FC Barcelona para a temporada 2025/26. As listras azuis e vermelhas do Barça com o DNA do futebol total."; tp="Clubes Europeus"; tags="clubes-europeus,barcelona,espanha,la-liga,champions-league"; p="129.90"; pc="179.90" },
    @{ h="camisa-barcelona-away-2526"; t="Camisa Barcelona Away 2025/26 | Barça"; d="Versão alternativa do Barcelona para 2025/26. O amarelo dourado do Barça fora do Camp Nou."; tp="Clubes Europeus"; tags="clubes-europeus,barcelona,espanha,la-liga"; p="129.90"; pc="179.90" },
    @{ h="camisa-psg-home-2526"; t="Camisa PSG Home 2025/26 | Paris Saint-Germain"; d="A camisa oficial do Paris Saint-Germain para a temporada 2025/26. O azul de Paris com Mbappé e a geração mais cara do futebol mundial."; tp="Clubes Europeus"; tags="clubes-europeus,psg,franca,ligue-1,champions-league"; p="129.90"; pc="179.90" },
    @{ h="camisa-psg-away-2526"; t="Camisa PSG Away 2025/26 | Paris Saint-Germain"; d="Versão alternativa do PSG para 2025/26. O branco parisiense com o estilo inconfundível do clube da Cidade Luz."; tp="Clubes Europeus"; tags="clubes-europeus,psg,franca,ligue-1"; p="129.90"; pc="179.90" },
    @{ h="camisa-manchester-city-home-2526"; t="Camisa Manchester City Home 2025/26 | Citizens"; d="A camisa oficial do Manchester City para a temporada 2025/26. O azul celeste dos Citizens com Haaland e o futebol de Pep Guardiola."; tp="Clubes Europeus"; tags="clubes-europeus,manchester-city,inglaterra,premier-league,champions-league"; p="129.90"; pc="179.90" },
    @{ h="camisa-manchester-city-away-2526"; t="Camisa Manchester City Away 2025/26 | Citizens"; d="Versão alternativa do Manchester City para 2025/26. Design elegante para os jogos fora do Etihad Stadium."; tp="Clubes Europeus"; tags="clubes-europeus,manchester-city,inglaterra,premier-league"; p="129.90"; pc="179.90" },
    @{ h="camisa-liverpool-home-2526"; t="Camisa Liverpool Home 2025/26 | The Reds"; d="A camisa oficial do Liverpool FC para a temporada 2025/26. O vermelho de Anfield com Salah e a lenda You'll Never Walk Alone."; tp="Clubes Europeus"; tags="clubes-europeus,liverpool,inglaterra,premier-league,champions-league"; p="129.90"; pc="179.90" },
    @{ h="camisa-liverpool-away-2526"; t="Camisa Liverpool Away 2025/26 | The Reds"; d="Versão alternativa do Liverpool para 2025/26. O verde vibrante dos Reds fora de Anfield."; tp="Clubes Europeus"; tags="clubes-europeus,liverpool,inglaterra,premier-league"; p="129.90"; pc="179.90" },
    @{ h="camisa-arsenal-home-2526"; t="Camisa Arsenal Home 2025/26 | Gunners"; d="A camisa oficial do Arsenal FC para a temporada 2025/26. O vermelho dos Gunners com Saka e Martinelli no Emirates Stadium."; tp="Clubes Europeus"; tags="clubes-europeus,arsenal,inglaterra,premier-league"; p="129.90"; pc="179.90" },
    @{ h="camisa-chelsea-home-2526"; t="Camisa Chelsea Home 2025/26 | Blues"; d="A camisa oficial do Chelsea FC para a temporada 2025/26. O azul royal dos Blues com o novo projeto no Stamford Bridge."; tp="Clubes Europeus"; tags="clubes-europeus,chelsea,inglaterra,premier-league"; p="129.90"; pc="179.90" },
    @{ h="camisa-manchester-united-home-2526"; t="Camisa Manchester United Home 2025/26 | Red Devils"; d="A camisa oficial do Manchester United para a temporada 2025/26. O vermelho eterno do Old Trafford em busca da glória perdida."; tp="Clubes Europeus"; tags="clubes-europeus,manchester-united,inglaterra,premier-league"; p="129.90"; pc="179.90" },
    @{ h="camisa-bayern-home-2526"; t="Camisa Bayern Munich Home 2025/26 | Die Roten"; d="A camisa oficial do Bayern de Munique para a temporada 2025/26. O vermelho bávaro do clube mais dominante do futebol alemão."; tp="Clubes Europeus"; tags="clubes-europeus,bayern-munich,alemanha,bundesliga,champions-league"; p="129.90"; pc="179.90" },
    @{ h="camisa-bayern-away-2526"; t="Camisa Bayern Munich Away 2025/26 | Die Roten"; d="Versão alternativa do Bayern de Munique para 2025/26. Branco elegante para os jogos fora da Allianz Arena."; tp="Clubes Europeus"; tags="clubes-europeus,bayern-munich,alemanha,bundesliga"; p="129.90"; pc="179.90" },
    @{ h="camisa-borussia-dortmund-home-2526"; t="Camisa Borussia Dortmund Home 2025/26 | BVB"; d="A camisa oficial do Borussia Dortmund para a temporada 2025/26. O amarelo e preto do BVB com o Signal Iduna Park mais barulhento da Europa."; tp="Clubes Europeus"; tags="clubes-europeus,borussia-dortmund,alemanha,bundesliga"; p="129.90"; pc="179.90" },
    @{ h="camisa-juventus-home-2526"; t="Camisa Juventus Home 2025/26 | Juve"; d="A camisa oficial da Juventus para a temporada 2025/26. As listras preto e branco da Vecchia Signora em busca do retorno ao topo."; tp="Clubes Europeus"; tags="clubes-europeus,juventus,italia,serie-a-italia"; p="129.90"; pc="179.90" },
    @{ h="camisa-ac-milan-home-2526"; t="Camisa AC Milan Home 2025/26 | Rossoneri"; d="A camisa oficial do AC Milan para a temporada 2025/26. O vermelho e preto dos Rossoneri com a história mais gloriosa do futebol italiano."; tp="Clubes Europeus"; tags="clubes-europeus,ac-milan,italia,serie-a-italia,champions-league"; p="129.90"; pc="179.90" },
    @{ h="camisa-inter-milan-home-2526"; t="Camisa Inter de Milão Home 2025/26 | Nerazzurri"; d="A camisa oficial da Inter de Milão para a temporada 2025/26. O azul e preto dos Nerazzurri do Stadio Giuseppe Meazza."; tp="Clubes Europeus"; tags="clubes-europeus,inter-milan,italia,serie-a-italia"; p="129.90"; pc="179.90" },
    @{ h="camisa-atletico-madrid-home-2526"; t="Camisa Atlético de Madrid Home 2025/26 | Colchoneros"; d="A camisa oficial do Atlético de Madrid para a temporada 2025/26. O vermelho e branco dos Colchoneros com Griezmann e Simeone."; tp="Clubes Europeus"; tags="clubes-europeus,atletico-madrid,espanha,la-liga"; p="129.90"; pc="179.90" },

    # ===== CAMISAS RETRÔ =====
    @{ h="camisa-brasil-retro-1970"; t="Camisa Brasil Retrô 1970 | Pelé | Copa México"; d="Reprodução da lendária camisa da Seleção Brasileira de 1970, usada por Pelé na conquista do tricampeonato no México. A camisa mais icônica da história do futebol."; tp="Retrô"; tags="retro,brasil,copa-do-mundo,classico,1970,pele"; p="89.90"; pc="129.90" },
    @{ h="camisa-brasil-retro-1994"; t="Camisa Brasil Retrô 1994 | Romário | Copa EUA"; d="Reprodução da camisa do tetracampeonato brasileiro em 1994 nos EUA. Com Romário, Bebeto e a geração de ouro que voltou a levantar a taça."; tp="Retrô"; tags="retro,brasil,copa-do-mundo,classico,1994,romario"; p="89.90"; pc="129.90" },
    @{ h="camisa-brasil-retro-2002"; t="Camisa Brasil Retrô 2002 | Ronaldo | Copa Japão/Coréia"; d="Reprodução da camisa do pentacampeonato em 2002. Ronaldo Fenômeno, R9, numa Copa do Mundo histórica no Japão e Coreia do Sul."; tp="Retrô"; tags="retro,brasil,copa-do-mundo,classico,2002,ronaldo-fenomeno"; p="89.90"; pc="129.90" },
    @{ h="camisa-argentina-retro-1986"; t="Camisa Argentina Retrô 1986 | Maradona | Copa México"; d="Reprodução da camisa histórica de Maradona em 1986. A camisa da mão de Deus e do gol do século. El Diego em seu melhor momento."; tp="Retrô"; tags="retro,argentina,copa-do-mundo,classico,1986,maradona"; p="89.90"; pc="129.90" },
    @{ h="camisa-franca-retro-1998"; t="Camisa França Retrô 1998 | Zidane | Copa França"; d="Reprodução da camisa da França campeã em 1998. Zidane, Thierry Henry e a geração que encantou o mundo no próprio país."; tp="Retrô"; tags="retro,franca,copa-do-mundo,classico,1998,zidane"; p="89.90"; pc="129.90" },
    @{ h="camisa-alemanha-retro-1990"; t="Camisa Alemanha Retrô 1990 | Copa Itália"; d="Reprodução da camisa da Alemanha Ocidental tricampeã em 1990. Matthäus, Klinsmann e a última Copa como Alemanha Ocidental."; tp="Retrô"; tags="retro,alemanha,copa-do-mundo,classico,1990"; p="89.90"; pc="129.90" },
    @{ h="camisa-italia-retro-1982"; t="Camisa Itália Retrô 1982 | Paolo Rossi | Copa Espanha"; d="Reprodução da camisa da Itália tricampeã em 1982. Paolo Rossi artilheiro e um dos Mundiais mais emocionantes da história."; tp="Retrô"; tags="retro,italia,copa-do-mundo,classico,1982"; p="89.90"; pc="129.90" },
    @{ h="camisa-holanda-retro-1988"; t="Camisa Holanda Retrô 1988 | Van Basten | Euro"; d="Reprodução da camisa da Holanda campeã da Eurocopa 1988. Van Basten, Gullit, Rijkaard — o triângulo mais temido do futebol europeu."; tp="Retrô"; tags="retro,holanda,euro,classico,1988,van-basten"; p="89.90"; pc="129.90" },
    @{ h="camisa-flamengo-retro-1981"; t="Camisa Flamengo Retrô 1981 | Zico | Libertadores"; d="Reprodução da camisa do Flamengo campeão da Libertadores e Mundial em 1981. Zico, o Galinho de Quintino, na maior conquista da história rubro-negra."; tp="Retrô"; tags="retro,flamengo,libertadores,classico,1981,zico,clubes-brasileiros"; p="89.90"; pc="129.90" },
    @{ h="camisa-corinthians-retro-2012"; t="Camisa Corinthians Retrô 2012 | Libertadores"; d="Reprodução da camisa do Corinthians campeão da Libertadores e Mundial em 2012. O título mais emocionante da história do Timão."; tp="Retrô"; tags="retro,corinthians,libertadores,classico,2012,clubes-brasileiros"; p="89.90"; pc="129.90" },
    @{ h="camisa-santos-retro-1962"; t="Camisa Santos Retrô 1962 | Pelé | Libertadores"; d="Reprodução da camisa do Santos de Pelé, bicampeão da Libertadores em 1962. O Rei do Futebol em seu clube do coração."; tp="Retrô"; tags="retro,santos,libertadores,classico,1962,pele,clubes-brasileiros"; p="89.90"; pc="129.90" },
    @{ h="camisa-real-madrid-retro-2002"; t="Camisa Real Madrid Retrô 2002 | Los Galácticos"; d="Reprodução da camisa do Real Madrid dos Galácticos em 2002. Zidane, Ronaldo, Figo, Roberto Carlos — o melhor time do mundo naquela época."; tp="Retrô"; tags="retro,real-madrid,champions-league,classico,2002,zidane,clubes-europeus"; p="89.90"; pc="129.90" },
    @{ h="camisa-barcelona-retro-2009"; t="Camisa Barcelona Retrô 2009 | Messi | Sextete"; d="Reprodução da camisa do Barcelona do Sextete em 2009. Messi, Xavi, Iniesta e Pep Guardiola no time mais dominante da história."; tp="Retrô"; tags="retro,barcelona,champions-league,classico,2009,messi,clubes-europeus"; p="89.90"; pc="129.90" },
    @{ h="camisa-psg-retro-2022"; t="Camisa PSG Retrô 2022 | Messi, Neymar, Mbappé"; d="Reprodução da camisa do PSG da temporada 2021/22 com Messi, Neymar e Mbappé. O ataque mais caro da história do futebol mundial."; tp="Retrô"; tags="retro,psg,franca,classico,2022,messi,neymar,mbappe,clubes-europeus"; p="89.90"; pc="129.90" },
    @{ h="camisa-milan-retro-2003"; t="Camisa AC Milan Retrô 2003 | Champions League"; d="Reprodução da camisa do Milan campeão da Champions de 2003. Shevchenko, Maldini, Pirlo — uma das equipes mais completas da história europeia."; tp="Retrô"; tags="retro,ac-milan,champions-league,classico,2003,maldini,clubes-europeus"; p="89.90"; pc="129.90" }
)

$output += $header

foreach ($p in $produtos) {
    $rows = New-Produto -handle $p.h -titulo $p.t -descricao $p.d -tipo $p.tp -tags $p.tags -preco $p.p -precoComparativo $p.pc
    $output += $rows
}

$output | Out-File -FilePath "C:\Users\seven\MazyOS\saidas\produtos-manto-dos-craques.csv" -Encoding utf8
Write-Host "Total de produtos: $($produtos.Count)"
Write-Host "Total de linhas no CSV: $($output.Count)"
Write-Host "Arquivo salvo em: C:\Users\seven\MazyOS\saidas\produtos-manto-dos-craques.csv"
