export type VehicleColor = { name: string; hex: string; image: string };
export type VehicleSpec = { label: string; value: string };
export type Vehicle = {
  id: string;
  slug: string;
  name: string;
  version: string;
  category: string;
  tagline: string;
  description: string;
  price: string;
  priceNote: string;
  badge: string | null;
  featured: boolean;
  hero: string;
  gallery: string[];
  colors: VehicleColor[];
  specs: VehicleSpec[];
  highlights: string[];
  compareSpecs: Record<string, string>;
};

export const vehicles: Vehicle[] = [
  {
    id: "haval-h6-hev",
    slug: "haval-h6-hev",
    name: "Haval H6",
    version: "HEV Ultra",
    category: "SUV Híbrido",
    tagline: "O SUV mais vendido do mundo. Agora híbrido.",
    description:
      "Espaço, conforto e tecnologia de ponta. Motor híbrido de 1.5T que combina desempenho com economia sem abrir mão de nenhuma comodidade.",
    price: "A consultar",
    priceNote: "Condições exclusivas com Alex Messias",
    badge: null,
    featured: true,
    hero: "/cars/haval-h6-hev/hero.jpg",
    gallery: [
      "/cars/haval-h6-hev/hero.jpg",
      "/cars/haval-h6-hev/azul.jpg",
      "/cars/haval-h6-hev/branco.webp",
      "/cars/haval-h6-hev/branco2.webp",
    ],
    colors: [
      { name: "Prata Titânio", hex: "#C0C0C0", image: "/cars/haval-h6-hev/hero.jpg" },
      { name: "Azul Cianita", hex: "#2A5C8E", image: "/cars/haval-h6-hev/azul.jpg" },
      { name: "Branco Aurora", hex: "#F5F5F5", image: "/cars/haval-h6-hev/branco.webp" },
    ],
    specs: [
      { label: "Motor", value: "1.5T HEV" },
      { label: "Potência", value: "243 cv (sistema)" },
      { label: "Torque", value: "530 Nm" },
      { label: "0–100 km/h", value: "7,9 s" },
      { label: "Câmbio", value: "DHT automático" },
      { label: "Tração", value: "4×2" },
      { label: "Tanque", value: "55 L" },
      { label: "Porta-malas", value: "529 L" },
      { label: "Garantia", value: "5 anos / 100.000 km" },
    ],
    highlights: [
      "Teto panorâmico elétrico",
      "Central multimídia 12,3″",
      "Painel digital 12,3″",
      "ACC com stop & go",
      "Câmera 360°",
      "Bancos em couro",
      "Keyless entry & start",
      "7 airbags",
    ],
    compareSpecs: {
      Motor: "1.5T HEV",
      Potência: "243 cv",
      Torque: "530 Nm",
      "0–100": "7,9 s",
      Tração: "4×2",
      Autonomia: "Convencional",
      Preço: "A consultar",
    },
  },
  {
    id: "haval-h6-phev19",
    slug: "haval-h6-phev19",
    name: "Haval H6",
    version: "PHEV19",
    category: "SUV Plug-in Híbrido",
    tagline: "Autonomia elétrica para a cidade. Combustão para qualquer distância.",
    description:
      "Plug-in híbrido de entrada com até 105 km de autonomia elétrica, performance de 220 cv e tração dianteira. A opção mais acessível da linha PHEV.",
    price: "A consultar",
    priceNote: "Condições exclusivas com Alex Messias",
    badge: "Plug-in",
    featured: true,
    hero: "/cars/haval-h6-phev19/hero.jpg",
    gallery: [
      "/cars/haval-h6-phev19/hero.jpg",
      "/cars/haval-h6-phev19/frente.avif",
      "/cars/haval-h6-phev19/branco.webp",
    ],
    colors: [
      { name: "Azul Cianita", hex: "#2A5C8E", image: "/cars/haval-h6-phev19/hero.jpg" },
      { name: "Branco Aurora", hex: "#F5F5F5", image: "/cars/haval-h6-phev19/branco.webp" },
    ],
    specs: [
      { label: "Motor", value: "1.5T + Motor elétrico" },
      { label: "Potência", value: "220 cv (sistema)" },
      { label: "Autonomia elétrica", value: "até 105 km" },
      { label: "0–100 km/h", value: "7,5 s" },
      { label: "Tração", value: "Dianteira" },
      { label: "Bateria", value: "19 kWh" },
      { label: "Carregamento AC", value: "3,3 kW" },
      { label: "Porta-malas", value: "510 L" },
      { label: "Garantia", value: "5 anos / 100.000 km" },
    ],
    highlights: [
      "105 km de autonomia elétrica",
      "Carregamento em tomada comum",
      "HUD Head-Up Display",
      "Teto panorâmico",
      "ACC com stop & go",
      "Câmera 360°",
      "Central 12,3″",
      "Driver Monitoring",
    ],
    compareSpecs: {
      Motor: "1.5T PHEV",
      Potência: "220 cv",
      Torque: "490 Nm",
      "0–100": "7,5 s",
      Tração: "Dianteira",
      Autonomia: "105 km (elétrica)",
      Preço: "A consultar",
    },
  },
  {
    id: "haval-h6-phev34",
    slug: "haval-h6-phev34",
    name: "Haval H6",
    version: "PHEV34",
    category: "SUV Plug-in Híbrido AWD",
    tagline: "Máximo desempenho. Máxima eficiência. AWD elétrico.",
    description:
      "A versão mais completa do H6 PHEV. Motor + elétrico com 326 cv, tração AWD elétrica e bateria de 37 kWh para até 105 km de autonomia pura.",
    price: "A consultar",
    priceNote: "Condições exclusivas com Alex Messias",
    badge: "AWD Premium",
    featured: true,
    hero: "/cars/haval-h6-phev34/hero.avif",
    gallery: [
      "/cars/haval-h6-phev34/hero.avif",
      "/cars/haval-h6-phev34/azul.jpg",
      "/cars/haval-h6-phev34/branco.webp",
    ],
    colors: [
      { name: "Branco Aurora", hex: "#F5F5F5", image: "/cars/haval-h6-phev34/branco.webp" },
      { name: "Azul Cianita", hex: "#2A5C8E", image: "/cars/haval-h6-phev34/azul.jpg" },
    ],
    specs: [
      { label: "Motor", value: "1.5T + Motor elétrico" },
      { label: "Potência", value: "326 cv (sistema)" },
      { label: "Torque", value: "600 Nm" },
      { label: "Autonomia elétrica", value: "até 105 km" },
      { label: "0–100 km/h", value: "6,5 s" },
      { label: "Tração", value: "AWD elétrico" },
      { label: "Bateria", value: "37 kWh" },
      { label: "Carregamento AC", value: "11 kW" },
      { label: "Garantia", value: "5 anos / 100.000 km" },
    ],
    highlights: [
      "AWD elétrico sem eixo mecânico",
      "326 cv de potência sistêmica",
      "105 km de autonomia elétrica",
      "Modos: EV / Híbrido / Sport",
      "HUD Head-Up Display",
      "Teto panorâmico duplo",
      "Bancos aquecidos e ventilados",
      "Driver Monitoring System",
    ],
    compareSpecs: {
      Motor: "1.5T PHEV34",
      Potência: "326 cv",
      Torque: "600 Nm",
      "0–100": "6,5 s",
      Tração: "AWD elétrico",
      Autonomia: "105 km (elétrica)",
      Preço: "A consultar",
    },
  },
  {
    id: "haval-h6-gt",
    slug: "haval-h6-gt",
    name: "Haval H6 GT",
    version: "HEV GT",
    category: "SUV Coupé Híbrido",
    tagline: "Design esportivo. Tecnologia híbrida. Tudo junto.",
    description:
      "SUV coupé com linhas esportivas únicas e motor HEV de 243 cv. Teto panorâmico, câmera 360° e interior premium em cada detalhe.",
    price: "A consultar",
    priceNote: "Condições exclusivas com Alex Messias",
    badge: "Mais Vendido",
    featured: true,
    hero: "/cars/haval-h6-gt/hero.webp",
    gallery: [
      "/cars/haval-h6-gt/hero.webp",
      "/cars/haval-h6-gt/azul.webp",
      "/cars/haval-h6-gt/branco.webp",
      "/cars/haval-h6-gt/azul2.webp",
    ],
    colors: [
      { name: "Preto Polar", hex: "#1A1A1A", image: "/cars/haval-h6-gt/hero.webp" },
      { name: "Azul Cianita", hex: "#2A5C8E", image: "/cars/haval-h6-gt/azul.webp" },
      { name: "Branco Aurora", hex: "#F5F5F5", image: "/cars/haval-h6-gt/branco.webp" },
    ],
    specs: [
      { label: "Motor", value: "1.5T HEV" },
      { label: "Potência", value: "243 cv (sistema)" },
      { label: "Torque", value: "530 Nm" },
      { label: "0–100 km/h", value: "7,6 s" },
      { label: "Câmbio", value: "DHT automático" },
      { label: "Carroceria", value: "SUV Coupé" },
      { label: "Teto", value: "Panorâmico elétrico" },
      { label: "Porta-malas", value: "529 L" },
      { label: "Garantia", value: "5 anos / 100.000 km" },
    ],
    highlights: [
      "Design coupé exclusivo",
      "Teto panorâmico elétrico",
      "Central multimídia 12,3″",
      "ACC com stop & go",
      "Câmera 360°",
      "Keyless entry & start",
      "Carregamento wireless",
      "7 airbags",
    ],
    compareSpecs: {
      Motor: "1.5T HEV GT",
      Potência: "243 cv",
      Torque: "530 Nm",
      "0–100": "7,6 s",
      Tração: "4×2",
      Autonomia: "Convencional",
      Preço: "A consultar",
    },
  },
  {
    id: "ora-03-skin",
    slug: "ora-03",
    name: "ORA 03",
    version: "Skin",
    category: "Sedan Elétrico",
    tagline: "100% elétrico. Design que não passa em branco.",
    description:
      "Sedan elétrico com design retrô-futurista único. Autonomia de até 401 km, carregamento rápido DC e tecnologia que impressiona.",
    price: "A consultar",
    priceNote: "Condições exclusivas com Alex Messias",
    badge: "Elétrico",
    featured: true,
    hero: "/cars/ora-03/hero.webp",
    gallery: [
      "/cars/ora-03/hero.webp",
      "/cars/ora-03/teal.jpg",
      "/cars/ora-03/cinza.jpg",
      "/cars/ora-03/interior.jpg",
      "/cars/ora-03/acao.jpg",
    ],
    colors: [
      { name: "Teal Vintage", hex: "#3A7A7A", image: "/cars/ora-03/teal.jpg" },
      { name: "Cinza Londrina", hex: "#8A8A8A", image: "/cars/ora-03/cinza.jpg" },
      { name: "Branco Pérola", hex: "#F5F5F0", image: "/cars/ora-03/hero.webp" },
    ],
    specs: [
      { label: "Motor", value: "Elétrico síncrono" },
      { label: "Potência", value: "171 cv" },
      { label: "Torque", value: "250 Nm" },
      { label: "Autonomia", value: "até 401 km (WLTP)" },
      { label: "Bateria", value: "63 kWh" },
      { label: "Carregamento DC", value: "80 kW (20–80% em 30 min)" },
      { label: "Carregamento AC", value: "11 kW" },
      { label: "0–100 km/h", value: "8,9 s" },
      { label: "Garantia", value: "5 anos / 100.000 km" },
    ],
    highlights: [
      "401 km de autonomia",
      "Carregamento rápido DC 80 kW",
      "Design retrô-futurista",
      "Central 10,25″",
      "Câmera 360°",
      "Apple CarPlay & Android Auto",
      "Ar dual zone",
      "Banco traseiro aquecido",
    ],
    compareSpecs: {
      Motor: "Elétrico",
      Potência: "171 cv",
      Torque: "250 Nm",
      "0–100": "8,9 s",
      Tração: "Dianteira",
      Autonomia: "401 km (elétrica)",
      Preço: "A consultar",
    },
  },
  {
    id: "ora-03-gt",
    slug: "ora-03-gt",
    name: "ORA 03 GT",
    version: "GT Performance",
    category: "Sedan Elétrico GT",
    tagline: "Performance elétrica sem compromisso.",
    description:
      "A versão GT traz mais potência, mais tecnologia e o mesmo design inconfundível. Para quem quer o elétrico mais esportivo da GWM.",
    price: "A consultar",
    priceNote: "Condições exclusivas com Alex Messias",
    badge: "GT",
    featured: false,
    hero: "/cars/ora-03/acao.jpg",
    gallery: [
      "/cars/ora-03/acao.jpg",
      "/cars/ora-03/hero.webp",
      "/cars/ora-03/interior.jpg",
    ],
    colors: [
      { name: "Teal Vintage", hex: "#3A7A7A", image: "/cars/ora-03/teal.jpg" },
      { name: "Preto Polar", hex: "#1A1A1A", image: "/cars/ora-03/acao.jpg" },
    ],
    specs: [
      { label: "Motor", value: "Elétrico síncrono GT" },
      { label: "Potência", value: "204 cv" },
      { label: "Torque", value: "340 Nm" },
      { label: "Autonomia", value: "até 380 km" },
      { label: "Bateria", value: "63 kWh" },
      { label: "Carregamento DC", value: "80 kW" },
      { label: "0–100 km/h", value: "7,1 s" },
      { label: "Garantia", value: "5 anos / 100.000 km" },
    ],
    highlights: [
      "204 cv de potência",
      "0 a 100 em 7,1 s",
      "Suspensão esportiva calibrada",
      "Diferencial eletrônico",
      "Bancos sport em couro",
      "Head-Up Display",
      "Câmera 360°",
      "Modo Sport exclusivo",
    ],
    compareSpecs: {
      Motor: "Elétrico GT",
      Potência: "204 cv",
      Torque: "340 Nm",
      "0–100": "7,1 s",
      Tração: "Dianteira",
      Autonomia: "380 km (elétrica)",
      Preço: "A consultar",
    },
  },
  {
    id: "tank-300",
    slug: "tank-300",
    name: "Tank 300",
    version: "Off-Road Luxury",
    category: "SUV Off-Road",
    tagline: "Aventura com requinte. Pista e trilha sem escolher.",
    description:
      "SUV off-road de luxo com visual imponente, blindagem estrutural e tecnologia topo de linha. Para quem não aceita limites.",
    price: "A consultar",
    priceNote: "Condições exclusivas com Alex Messias",
    badge: "Off-Road",
    featured: false,
    hero: "/cars/tank-300/hero.webp",
    gallery: [
      "/cars/tank-300/hero.webp",
      "/cars/tank-300/prata.jpg",
    ],
    colors: [
      { name: "Preto Polar", hex: "#1A1A1A", image: "/cars/tank-300/hero.webp" },
      { name: "Prata Titânio", hex: "#C0C0C0", image: "/cars/tank-300/prata.jpg" },
    ],
    specs: [
      { label: "Motor", value: "2.0T GDI" },
      { label: "Potência", value: "227 cv" },
      { label: "Torque", value: "387 Nm" },
      { label: "0–100 km/h", value: "8,5 s" },
      { label: "Tração", value: "4WD com reduzida" },
      { label: "Câmbio", value: "8 velocidades" },
      { label: "Vão livre", value: "224 mm" },
      { label: "Tanque", value: "70 L" },
      { label: "Garantia", value: "5 anos / 100.000 km" },
    ],
    highlights: [
      "Tração 4WD com reduzida",
      "Capacidade de rampa 30°",
      "Travamento de diferencial",
      "Câmera 360° + câmera traseira HD",
      "Central multimídia 12,3″",
      "Teto panorâmico",
      "Ar-condicionado dual zone",
      "7 airbags",
    ],
    compareSpecs: {
      Motor: "2.0T GDI",
      Potência: "227 cv",
      Torque: "387 Nm",
      "0–100": "8,5 s",
      Tração: "4WD + reduzida",
      Autonomia: "—",
      Preço: "A consultar",
    },
  },
];

export const testimonials = [
  { id: 1, name: "Ricardo Almeida", location: "Campinas, SP", vehicle: "Haval H6 GT", text: "O Alex me ajudou em tudo desde a escolha do modelo até a entrega. Atendimento diferenciado, sem pressão. Recomendo muito.", rating: 5 },
  { id: 2, name: "Fernanda Costa", location: "Jundiaí, SP", vehicle: "ORA 03", text: "Fui atendida de forma personalizada, tirou todas as dúvidas sobre o elétrico. Saí de lá com confiança total na compra.", rating: 5 },
  { id: 3, name: "Marcos Pereira", location: "São Paulo, SP", vehicle: "Haval H6 PHEV34", text: "Profissional que realmente conhece os veículos. Me ajudou a entender o plug-in híbrido e tomar a melhor decisão.", rating: 5 },
  { id: 4, name: "Juliana Santos", location: "Campinas, SP", vehicle: "Haval H6 HEV", text: "Processo rápido, transparente e sem surpresas. Alex cuidou de tudo com excelência. Já indiquei para amigos.", rating: 5 },
  { id: 5, name: "Eduardo Lima", location: "Jundiaí, SP", vehicle: "Tank 300", text: "Queria algo para cidade e trilha. O Alex entendeu minha necessidade na hora e me mostrou o Tank 300. Decisão certa.", rating: 5 },
  { id: 6, name: "Camila Rocha", location: "Campinas, SP", vehicle: "Haval H6 PHEV19", text: "O primeiro carro elétrico da família. Alex explicou tudo sobre carregamento, autonomia e custo. Confiança total.", rating: 5 },
];

export const differentials = [
  { icon: "user", title: "Atendimento Consultivo", description: "Cada cliente recebe atenção exclusiva. Sem pressão, sem pressa. No seu ritmo e no seu tempo." },
  { icon: "award", title: "Especialista GWM", description: "Conhecimento técnico profundo em todos os modelos — HEV, PHEV, elétrico e off-road." },
  { icon: "car", title: "Test Drive Personalizado", description: "Agende sem burocracia. Sinta o veículo antes de decidir. Na sua rotina, no seu caminho." },
  { icon: "shield", title: "Financiamento Facilitado", description: "Aprovação nos principais bancos. Simulações sem compromisso e condições diferenciadas." },
  { icon: "trending-up", title: "Avaliação do Seu Usado", description: "Avalie seu veículo atual com transparência e use como entrada no seu novo GWM." },
  { icon: "map-pin", title: "Entrega em toda a Região", description: "Campinas, Jundiaí, São Paulo e cidades próximas. Você escolhe onde receber." },
  { icon: "headphones", title: "Pós-venda de Verdade", description: "Suporte contínuo após a entrega. Dúvidas sobre o veículo? Alex está disponível." },
  { icon: "star", title: "Consórcio Sem Juros", description: "Condições exclusivas em consórcio GWM. Planeje sua compra com parcelas que cabem no bolso." },
];

export const galleryImages = [
  { src: "/cars/haval-h6-gt/hero.webp", alt: "Haval H6 GT" },
  { src: "/images/gallery/dealership.jpg", alt: "Showroom GWM" },
  { src: "/cars/ora-03/hero.webp", alt: "ORA 03" },
  { src: "/images/gallery/lineup-dusk.png", alt: "Linha GWM" },
  { src: "/cars/haval-h6-gt/azul.webp", alt: "H6 GT Azul" },
  { src: "/images/gallery/das-1.webp", alt: "GWM" },
  { src: "/cars/ora-03/teal.jpg", alt: "ORA 03 Teal" },
  { src: "/images/gallery/h6-divulgacao.webp", alt: "H6" },
  { src: "/images/gallery/das-1b.webp", alt: "GWM" },
  { src: "/cars/ora-03/interior.jpg", alt: "Interior ORA 03" },
  { src: "/images/gallery/haval-h6-27.avif", alt: "Haval H6" },
  { src: "/cars/haval-h6-hev/hero.jpg", alt: "H6 HEV" },
];

export const siteConfig = {
  whatsapp: "5519999999999",
  phone: "(19) 9 9999-9999",
  email: "alex@alexmessias.com.br",
  instagram: "https://www.instagram.com/alexmessiasoficial/",
  locations: ["Campinas", "Jundiaí", "São Paulo"],
};

export const compareModels = ["haval-h6-hev", "haval-h6-gt", "haval-h6-phev34"];
